import { parseWorkflowDefinition } from "./definition";

export const defaultCaseWorkflowDefinition = parseWorkflowDefinition({
  schemaVersion: 1,
  initialState: "intake_review",
  states: [
    { key: "intake_review", label: "Intake review" },
    { key: "accepted", label: "Accepted" },
    { key: "rejected", label: "Rejected" },
    { key: "open", label: "Open" },
    { key: "resolved", label: "Resolved" },
    { key: "closed", label: "Closed" },
  ],
  transitions: [
    {
      key: "accept_intake",
      label: "Accept intake",
      from: "intake_review",
      to: "accepted",
      requiredPermissions: ["case:update"],
    },
    {
      key: "reject_intake",
      label: "Reject intake",
      from: "intake_review",
      to: "rejected",
      requiredPermissions: ["case:update"],
    },
    {
      key: "open_accepted_case",
      label: "Open case",
      from: "accepted",
      to: "open",
      requiredPermissions: ["case:update"],
      actions: [{ type: "mark_open" }],
    },
    {
      key: "return_accepted_to_intake",
      label: "Return to intake review",
      from: "accepted",
      to: "intake_review",
      requiredPermissions: ["case:update"],
    },
    {
      key: "reconsider_rejected_intake",
      label: "Reconsider",
      from: "rejected",
      to: "intake_review",
      requiredPermissions: ["case:update"],
    },
    {
      key: "resolve_open_case",
      label: "Resolve case",
      from: "open",
      to: "resolved",
      requiredPermissions: ["case:update"],
      actions: [{ type: "mark_resolved" }],
    },
    {
      key: "close_open_case",
      label: "Close case",
      from: "open",
      to: "closed",
      requiredPermissions: ["case:close"],
      actions: [{ type: "mark_closed" }],
    },
    {
      key: "reopen_resolved_case",
      label: "Reopen case",
      from: "resolved",
      to: "open",
      requiredPermissions: ["case:update"],
      actions: [{ type: "mark_open" }],
    },
    {
      key: "close_resolved_case",
      label: "Close case",
      from: "resolved",
      to: "closed",
      requiredPermissions: ["case:close"],
      actions: [{ type: "mark_closed" }],
    },
    {
      key: "reopen_closed_case",
      label: "Reopen case",
      from: "closed",
      to: "open",
      requiredPermissions: ["case:update"],
      actions: [{ type: "mark_open" }],
    },
  ],
});
