export const corePermissions = [
  "organization:view",
  "organization:manage",
  "membership:view",
  "membership:manage",
  "office:view",
  "office:manage",
  "role:view",
  "role:manage",
  "invitation:manage",
  "form:view",
  "form:manage",
  "workflow:view",
  "workflow:manage",
  "routing:view",
  "routing:manage",
  "submission:view",
  "case:create",
  "case:view",
  "case:assign",
  "case:update",
  "case:close",
  "case:appeal",
  "review:view",
  "review:file",
  "review:assign",
  "review:decide",
  "review:manage",
  "deadline:view",
  "deadline:operate",
  "deadline:manage",
  "document:view",
  "document:upload",
  "document:manage",
  "document:scan_manage",
  "document:view_private",
  "disclosure:view",
  "disclosure:prepare",
  "disclosure:review",
  "disclosure:publish",
  "note:view",
  "note:create_internal",
  "note:create_participant",
  "correspondence:view",
  "correspondence:manage",
  "communication:template_manage",
  "notification:view",
  "notification:manage",
  "job:view",
  "job:manage",
  "audit:view",
  "api:manage",
  "webhook:manage",
] as const;

export type CorePermission = (typeof corePermissions)[number];
export type Permission = CorePermission | (string & {});

export interface RoleTemplate {
  key: string;
  name: string;
  description: string;
  permissions: readonly CorePermission[];
}

export const defaultRoleTemplates: readonly RoleTemplate[] = [
  {
    key: "administrator",
    name: "Administrator",
    description: "Full organization administration and operational access.",
    permissions: corePermissions,
  },
  {
    key: "supervisor",
    name: "Supervisor",
    description: "Operational supervision without organization security administration.",
    permissions: [
      "disclosure:publish",
      "disclosure:review",
      "disclosure:prepare",
      "disclosure:view",
      "review:manage",
      "review:decide",
      "review:assign",
      "review:file",
      "review:view",
      "job:manage",
      "job:view",
      "notification:manage",
      "notification:view",
      "communication:template_manage",
      "correspondence:manage",
      "correspondence:view",
      "note:create_participant",
      "note:view",
      "organization:view",
      "membership:view",
      "office:view",
      "role:view",
      "form:view",
      "workflow:view",
      "routing:view",
      "routing:manage",
      "submission:view",
      "case:create",
      "case:view",
      "case:assign",
      "case:update",
      "case:close",
      "case:appeal",
      "deadline:view",
      "deadline:operate",
      "deadline:manage",
      "document:view",
      "document:manage",
      "document:scan_manage",
      "document:upload",
      "document:view_private",
      "note:create_internal",
      "audit:view",
    ],
  },
  {
    key: "case_worker",
    name: "Case Worker",
    description: "Standard case-processing access.",
    permissions: [
      "review:file",
      "review:view",
      "notification:view",
      "correspondence:manage",
      "correspondence:view",
      "note:create_participant",
      "note:view",
      "organization:view",
      "office:view",
      "form:view",
      "workflow:view",
      "routing:view",
      "submission:view",
      "case:create",
      "case:view",
      "case:update",
      "deadline:view",
      "deadline:operate",
      "document:view",
      "document:upload",
      "document:view_private",
      "note:create_internal",
    ],
  },
  {
    key: "intake_reviewer",
    name: "Intake Reviewer",
    description: "Intake and preliminary review access.",
    permissions: [
      "review:file",
      "review:view",
      "notification:view",
      "correspondence:view",
      "note:view",
      "organization:view",
      "office:view",
      "form:view",
      "workflow:view",
      "routing:view",
      "submission:view",
      "case:create",
      "case:view",
      "case:update",
      "deadline:view",
      "deadline:operate",
      "document:view",
      "document:upload",
      "document:view_private",
    ],
  },
  {
    key: "reviewer",
    name: "Reviewer",
    description: "Independent review and appeal access.",
    permissions: [
      "review:decide",
      "review:file",
      "review:view",
      "notification:view",
      "correspondence:view",
      "note:view",
      "organization:view",
      "office:view",
      "form:view",
      "workflow:view",
      "routing:view",
      "submission:view",
      "case:view",
      "case:appeal",
      "deadline:view",
      "document:view",
      "document:view_private",
      "audit:view",
    ],
  },
  {
    key: "auditor",
    name: "Auditor",
    description: "Read-only oversight and audit access.",
    permissions: [
      "disclosure:view",
      "review:view",
      "job:view",
      "notification:view",
      "correspondence:view",
      "note:view",
      "organization:view",
      "membership:view",
      "office:view",
      "role:view",
      "form:view",
      "workflow:view",
      "routing:view",
      "submission:view",
      "case:view",
      "deadline:view",
      "document:view",
      "document:view_private",
      "audit:view",
    ],
  },
  {
    key: "submitter",
    name: "Submitter",
    description: "External participant access to permitted submission workflows.",
    permissions: ["case:create"],
  },
];
